version: '3'

services:
  shieldy:
    build: .
    restart: always
    networks:
      - app-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #   networks:
  #     - app-network
  #   depends_on:
  #     - mongo

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: